[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"